name: build

on:
  - push


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    name: node-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint -- --quiet # errors only, no warnings
        name: eslint
      - run: npm run test
      - uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: coverage/junit.xml
        if: matrix.node == 12
